export const productos = [
  {
    id: 0,
    producto: "Bloques con perrito",
    imagen: "./assets/images/blocks-dog.png",
    descripcion: "Perrito",
    precio: 71.99,
    categoria: "0-1",
    subcategoria: "puzzles",
  },
  {
    id: 1,
    producto: "Conejitos",
    imagen: "./assets/images/bunnies.jpg",
    descripcion: "Dos conejitos de madera",
    precio: 52.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 2,
    producto: "Conejito",
    imagen: "./assets/images/bunny-toddler.jpg",
    descripcion: "Conejito con carrito",
    precio: 59.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 3,
    producto: "Calendario",
    imagen: "./assets/images/calendar.png",
    descripcion: "Calendario para aprender los diás y las fechas",
    precio: 56.99,
    categoria: "3+",
    subcategoria: "didacticos",
  },
  {
    id: 4,
    producto: "Cámara de fotos",
    imagen: "./assets/images/camara.jpg",
    descripcion:
      "Este juguete está pensado para potenciar la creatividad y desarrollar la habilidad de observación. <br> Los niños podrán disfutar del juguete en casa o al aire libre, observando a través del lente el entorno que les rodea y la belleza de la naturaleza. <br> La observación hace que los niños aprendan a estar atentos de las cosas que suceden a su alrededor y ayuda a desarrollar otras habilidades cognitivas.",
    edad: "Para niños mayores de dos años",
    precio: 89.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 5,
    producto: "Carrusel",
    imagen: "./assets/images/carrusel.png",
    descripcion: "Caja musical con tapadera en forma de carusel",
    precio: 91.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 6,
    producto: "Camaleón",
    imagen: "./assets/images/chameleon_baby.jpg",
    descripcion: "Camaleón de color verde con ruedas",
    precio: 54.99,
    categoria: "0-1",
    subcategoria: "animales",
  },
  {
    id: 7,
    producto: "Relój",
    imagen: "./assets/images/clock.jpg",
    descripcion: "Es hora de aprender las horas del relój",
    precio: 45.99,
    categoria: "3+",
    subcategoria: "didacticos",
  },
  {
    id: 8,
    producto: "Cafetera",
    imagen: "./assets/images/coffeemachine.jpg",
    descripcion: "Cafetera con taza y cucharita",
    precio: 79.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 9,
    producto: "Vacas",
    imagen: "./assets/images/cows.jpg",
    descripcion: "Una familia feliz de vacas pastando",
    precio: 32.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 10,
    producto: "Bloques con letras",
    imagen: "./assets/images/cubes-baby.jpg",
    descripcion: "Bloques d emadera con las letras del abecedario",
    precio: 32.99,
    categoria: "1-3",
    subcategoria: "puzzles",
  },
  {
    id: 11,
    producto: "Ciervos",
    imagen: "./assets/images/deer.jpg",
    descripcion: "Mamá cierva con su bebé cervatillo",
    precio: 34.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 12,
    producto: "Zorros",
    imagen: "./assets/images/fox.jpg",
    descripcion: "Una pareja de zorros disfrutando del sol",
    precio: 37.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 13,
    producto: "Set jardinería",
    imagen: "./assets/images/garden.jpg",
    descripcion:
      "Si te gusta cuidar de las plantas de tu jardín este será tu set preferido",
    precio: 78.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 14,
    producto: "Helicóptero",
    imagen: "./assets/images/hellicopter.jpg",
    descripcion: "Pequeño helicóptero con ruedas",
    precio: 34.99,
    categoria: "1-3",
    subcategoria: "vehiculos",
  },
  {
    id: 15,
    producto: "Hipopótamo",
    imagen: "./assets/images/hippo.png",
    descripcion: "Un hipopótamo dandose un paseo",
    precio: 53.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 16,
    producto: "Todoterreno",
    imagen: "./assets/images/jeep.png",
    descripcion:
      "Un todoterreno que consigue atravesar los terrenos más difíciles",
    precio: 45.99,
    categoria: "3+",
    subcategoria: "vehiculos",
  },
  {
    id: 17,
    producto: "Tablas con los números",
    imagen: "./assets/images/numbers.jpg",
    descripcion: "Te gustaría aprender los números hasta 10?",
    precio: 35.99,
    categoria: "3+",
    subcategoria: "puzzles",
  },
  {
    id: 18,
    producto: "Puzzle circulos",
    imagen: "./assets/images/puzzle-circles.jpg",
    descripcion:
      "Un puzzle en forma de torre compuesto de circulos. No hay un orden correcto! Puedes apilarlos como te guste",
    precio: 34.99,
    categoria: "1-3",
    subcategoria: "puzzles",
  },
  {
    id: 19,
    producto: "Puzzle Dino",
    imagen: "./assets/images/puzzle-dino-baby.jpg",
    descripcion: "Un divertido puzzle en forma de dinosaurio",
    precio: 45.99,
    categoria: "1-3",
    subcategoria: "puzzles",
  },
  {
    id: 20,
    producto: "Puzzle Fresa",
    imagen: "./assets/images/puzzle-strawberry.jpg",
    descripcion: "Un divertido puzzle en forma de fresa",
    precio: 35.99,
    categoria: "1-3",
    subcategoria: "puzzles",
  },
  {
    id: 21,
    producto: "Rinoceronte",
    imagen: "./assets/images/rhino-baby.jpg",
    descripcion: "Un bonito rinoceronte con ruedas",
    precio: 37.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 22,
    producto: "Cohete",
    imagen: "./assets/images/rocket+human.jpg",
    descripcion: "Un cohete ultra rápido para explorar el espacio!",
    precio: 31.99,
    categoria: "1-3",
    subcategoria: "vehiculos",
  },
  {
    id: 23,
    producto: "Safari",
    imagen: "./assets/images/set_safari.jpg",
    descripcion: "Te apetece un safari por la Sabana?",
    precio: 56.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 24,
    producto: "Set cocina",
    imagen: "./assets/images/set-kitchen.jpg",
    descripcion:
      "Qué divertido es cocinar! De qué equipo eres, ¿dulce o salado?",
    precio: 95.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 25,
    producto: "Set matematicas",
    imagen: "./assets/images/set-math3.jpg",
    descripcion: "Te apetece aprender a sumar y restar con bolitas fluffy?",
    precio: 34.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 26,
    producto: "Hora del té",
    imagen: "./assets/images/set-tea-time.png",
    descripcion:
      "Ya es la hora del té? Esta será tu vajilla favorita de ahora en adelante!",
    precio: 85.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 27,
    producto: "Animales del bosque",
    imagen: "./assets/images/set-wood.jpg",
    descripcion:
      "Un set en el que te puedes adentrar al bosque y conocer sus habitantes. Quizas os hacéis amigos!",
    precio: 57.99,
    categoria: "3+",
    subcategoria: "sets",
  },
  {
    id: 28,
    producto: "Ovejitas",
    imagen: "./assets/images/sheeps.jpg",
    descripcion:
      "Unas cuantas amables oevjitas pastando en el monte y disfrutando de su tranquilidad",
    precio: 31.99,
    categoria: "1-3",
    subcategoria: "animales",
  },
  {
    id: 29,
    producto: "Taxi",
    imagen: "./assets/images/taxi.png",
    descripcion:
      "El taxi más molón de la ciudad! Donde llevarás a tus amigos con tu nuevo coche?",
    precio: 51.99,
    categoria: "3+",
    subcategoria: "vehiculos",
  },
  {
    id: 30,
    producto: "Tren",
    imagen: "./assets/images/train.jpg",
    descripcion: "Quien se monta al tren más rápido? Tu-tuuu!",
    precio: 51.99,
    categoria: "1-3",
    subcategoria: "vehiculos",
  },
  {
    id: 31,
    producto: "Extreterrestre",
    imagen: "./assets/images/ufo-alien.png",
    descripcion: "El extraterrestre más molón del Sistema Solar!",
    precio: 39.99,
    categoria: "3+",
    subcategoria: "vehiculos",
  },
  {
    id: 32,
    producto: "Estación meteorológica",
    imagen: "./assets/images/weather.jpg",
    descripcion:
      "Sabes qué tiempo hace fuera? Si la respuesta es no, yo te ayudaré a aprender!",
    precio: 54.99,
    categoria: "3+",
    subcategoria: "didacticos",
  },
  {
    id: 33,
    producto: "Leñador",
    imagen: "./assets/images/woodcutter.jpg",
    descripcion:
      "Un leñador que está recogiendo leña para que su familia esté calentita. Le ayudas?",
    precio: 31.99,
    categoria: "1-3",
    subcategoria: "vehiculos",
  },
  {
    id: 34,
    producto: "Puzzle abstracto",
    imagen: "./assets/images/wooden-rokcs.jpg",
    descripcion:
      "Son rocas o es madera? Te he pillado! Es madera! A ver si puedes hacer una torre sin que se caiga!",
    precio: 39.99,
    categoria: "1-3",
    subcategoria: "puzzles",
  },
  {
    id: 35,
    producto: "Palabras",
    imagen: "./assets/images/words.jpg",
    descripcion:
      "Sabes como se forman las palabras? Si conoces el abecedario ya tienes medio camino camino hecho! Esto será pan comido!",
    precio: 31.99,
    categoria: "3+",
    subcategoria: "didacticos",
  },
];
